mystic_chest_spawn_message: §dМистический груз заспавнился на координатах %x %y %z §aда начнётся борьба!
mysterious_chest_spawn_message: §dТаинственный груз заспавнился на координатах %x %y %z §aда начнётся борьба!

mystic_chest_coordinate: 2000 # Максимальная координата от спавна в минус и плюс
mysterious_chest_coordinate: 2000 # Максимальная координата от спавна в минус и плюс

#Not working
#mystic_chest_timer_hologram: §dМистический груз / Осталось %m:%s
#mysterious_chest_timer_hologram: §dТаинственный груз / Осталось %m:%s

mystic_chest_closed_hologram:
  - "&dМистический груз / &cНедоступен"
  - "До появления груза: %m %s"
mysterious_chest_closed_hologram:
  - "&dТаинственный груз / &cНедоступен"
  - "До появления груза: %m %s"

mystic_chest_opened_hologram:
  - "&dМистический груз / &aДоступен"
mysterious_chest_opened_hologram:
  - "&dТаинственный груз / &aДоступен"

mystic_chest_opened_message: Игрок %player успешно залутал мистический на координатах %x, %y, %z и скрылся с ценными вещичками.
mysterious_chest_opened_message: Игрок %player успешно залутал таинственный груз на координатах %x, %y, %z и скрылся с ценными вещичками.

mystic_chest_spawn_15m_message: §dМистический груз появится на координатах %x %y %z через 15 минут, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_10m_message: §dМистический груз появится на координатах %x %y %z через 10 минут, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_5m_message: §dМистический груз появится на координатах %x %y %z через 5 минут, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_3m_message: §dМистический груз появится на координатах %x %y %z через 3 минуты, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_1m_message: §dМистический груз появится на координатах %x %y %z через 1 минуту, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_30s_message: §dМистический груз появится на координатах %x %y %z через 30 секунд, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_15s_message: §dМистический груз появится на координатах %x %y %z через 15 секунд, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_5s_message: §dМистический груз появится на координатах %x %y %z через 5 секунд, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_4s_message: §dМистический груз появится на координатах %x %y %z через 4 секунды, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_3s_message: §dМистический груз появится на координатах %x %y %z через 3 секунды, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_2s_message: §dМистический груз появится на координатах %x %y %z через 2 секунды, быстрей найдите его и заберите тонны ценного лута
mystic_chest_spawn_1s_message: §dМистический груз появится на координатах %x %y %z через 1 секунду, быстрей найдите его и заберите тонны ценного лута

mysterious_chest_spawn_30m_message: §dТаинственный груз появится на координатах %x %y %z через 30 минут, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_15m_message: §dТаинственный груз появится на координатах %x %y %z через 15 минут, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_10m_message: §dТаинственный груз появится на координатах %x %y %z через 10 минут, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_5m_message: §dТаинственный груз появится на координатах %x %y %z через 5 минут, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_3m_message: §dТаинственный груз появится на координатах %x %y %z через 3 минуты, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_1m_message: §dТаинственный груз появится на координатах %x %y %z через 1 минуту, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_30s_message: §dТаинственный груз появится на координатах %x %y %z через 30 секунд, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_15s_message: §dТаинственный груз появится на координатах %x %y %z через 15 секунд, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_5s_message: §dТаинственный груз появится на координатах %x %y %z через 5 секунд, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_4s_message: §dТаинственный груз появится на координатах %x %y %z через 4 секунды, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_3s_message: §dТаинственный груз появится на координатах %x %y %z через 3 секунды, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_2s_message: §dТаинственный груз появится на координатах %x %y %z через 2 секунды, быстрей найдите его и заберите тонны ценного лута
mysterious_chest_spawn_1s_message: §dТаинственный груз появится на координатах %x %y %z через 1 секунду, быстрей найдите его и заберите тонны ценного лута